name: checkflow
description: >
  A lightweight and modular checklist manager for mobile.
  Allows creating structured checklists, attaching photos to each item,
  and exporting the entire flow for desktop report generation.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter_riverpod: ^2.6.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  archive: ^4.0.7
  share_plus: ^12.0.1

dev_dependencies:
  build_runner: ^2.10.5
  drift_dev: ^2.30.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
